### ISSUE TITLE
GatLab CI error: write EPIPE

### ISSUE THREAD

**Issue by leewp14** [chenzhutian/hexo-all-minifier#51]
![image](https://user-images.githubusercontent.com/17796518/36070111-2c3cc90a-0f2f-11e8-82b2-871019816034.png)
Any idea? Using GitLab CI (runner)

**Comment by InitNext** [comment]
I meet the same problem in Travis CI

**Comment by chenzhutian** [comment]
Could you please provide more info?
For example the node version

**Comment by leewp14** [comment]
[raw.txt](https://github.com/chenzhutian/hexo-all-minifier/files/1765910/raw.txt)
attached is the output of runner. node version is 6.10.0 as stated in above log file.

**Comment by maple3142** [comment]
Also happened in travis-ci.
[logs](https://travis-ci.org/maple3142/Blog/builds/362011736)

**Comment by chenzhutian** [comment]
@maple3142 @InitNext @leewp14 
This bug may be related to this issues of imagemin-mozjpeg https://github.com/imagemin/imagemin-mozjpeg/issues/28
It can be fixed by `sudo apt-get install libpng16-dev`.
However, the `libpng16-dev` is not in the whitelist of Travis-CI so that it cannot be installed during the building.
To fix it, please change the `os` in your `travis.yml` file to `os: osx`
(And then maybe you need to install `libpng16-dev` before the CI starting to build. I am not sure because I'm not familiar with `osx`)
